PATCH /api/2.5/auctions/0a3e5825752c49199ced43de14247e09/awards/6db7e816045d472988cfe99940d2e89f?acc_token=72db756788834611b45a27690fa30121 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 33
Content-Type: application/json
Host: lb.api-sandbox.registry.ea.openprocurement.net
DATA:
{
  "data": {
    "status": "cancelled"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "cancelled", 
    "complaintPeriod": {
      "startDate": "2018-12-07T19:32:47.965330+02:00", 
      "endDate": "2018-12-07T19:32:48.134849+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "bid_id": "16331e49f073425798ea4f18f3590c95", 
    "value": {
      "currency": "UAH", 
      "amount": 469, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-12-07T19:32:48.142167+02:00", 
    "id": "6db7e816045d472988cfe99940d2e89f"
  }
}

