PATCH /api/2.5/auctions/17a42b23eaed4286a8937da1348817bb/awards/4e8136ff281a4f97aca77361f2e29641?acc_token=b08a569f0fc244778d05c70166974957 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 146
Content-Type: application/json
Host: https://lb.api-sandbox.ea2.openprocurement.net/api/2.3/auctions
DATA:
{
  "data": {
    "status": "unsuccessful", 
    "description": "Candidate didn’t sign the auction protocol in 3 business days", 
    "title": "Disqualified"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "unsuccessful", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "bid_owner", 
        "title": "auction_protocol.pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/f7bfc14aee6f407dbce67342bec27cfe?KeyID=172d32c8&Signature=Z2WHBaMxm15G%252BTbq%2F5DNaCRA05rZV9F0XK1yx2%2FnywzB5d5aNfCSJSW1S6vYZleOfvx%252B11CBfXTAfe34x%2FYYCg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "auction", 
        "datePublished": "2019-01-28T12:32:16.391113+02:00", 
        "documentType": "auctionProtocol", 
        "dateModified": "2019-01-28T12:32:16.391142+02:00", 
        "id": "81dd291ccb2342628e48c70e22593b4d"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "auction_owner", 
        "title": "RejectionProtocol.pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/990c527a9fe34b218bcb6330691b6a3a?KeyID=172d32c8&Signature=npfcCCOLpOyFNfnK9p0RC4z5%252BMbLIAozLJ4nOE0tw033hfeLUdS%252BFndF4MtD8MZPw86N%2FG79eG%2F62fpy54S9BQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "auction", 
        "datePublished": "2019-01-28T12:32:16.508364+02:00", 
        "documentType": "rejectionProtocol", 
        "dateModified": "2019-01-28T12:32:16.508385+02:00", 
        "id": "b743cbdfd1444110bfdf3740457ddff1"
      }
    ], 
    "verificationPeriod": {
      "startDate": "2019-01-28T12:32:16.245982+02:00", 
      "endDate": "2019-01-28T12:32:16.660016+02:00"
    }, 
    "description": "Candidate didn’t sign the auction protocol in 3 business days", 
    "title": "Disqualified", 
    "suppliers": [
      {
        "additionalIdentifiers": [
          {
            "scheme": "UA-FIN", 
            "id": "А01 457213"
          }
        ], 
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "complaintPeriod": {
      "startDate": "2019-01-28T12:32:15.706689+02:00", 
      "endDate": "2019-01-28T12:32:16.660016+02:00"
    }, 
    "bid_id": "9d7e4eed27534b56b663ea362332e0ab", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-01-28T12:32:16.672132+02:00", 
    "id": "4e8136ff281a4f97aca77361f2e29641", 
    "signingPeriod": {
      "startDate": "2019-01-28T12:32:16.245982+02:00", 
      "endDate": "2019-02-18T18:00:00+02:00"
    }
  }
}

