PATCH /api/2.5/auctions/e0c4d484a95140569171138086703f23/awards/24f7e995bebe479d8acf5d3a9337ff3d?acc_token=898cfa971bac42239310ee094fdb7b78 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 33
Content-Type: application/json
Host: https://lb.api-sandbox.ea2.openprocurement.net/api/2.3/auctions
DATA:
{
  "data": {
    "status": "cancelled"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "cancelled", 
    "complaintPeriod": {
      "startDate": "2019-01-28T12:32:19.988125+02:00", 
      "endDate": "2019-01-28T12:32:20.223166+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "bid_id": "f59572206a724c87901cfd00ff8244ff", 
    "value": {
      "currency": "UAH", 
      "amount": 469, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-01-28T12:32:20.234410+02:00", 
    "id": "24f7e995bebe479d8acf5d3a9337ff3d"
  }
}

