PATCH /api/2.5/auctions/db1ca318fa4d4408a0d96e29ab6e5142/awards/7fea1585f8ff49e88f750a9f89080ce2?acc_token=ba6a7bfc110748baae5dbc8072efd550 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 146
Content-Type: application/json
Host: lb.api-sandbox.registry.ea.openprocurement.net
DATA:
{
  "data": {
    "status": "unsuccessful", 
    "description": "Candidate didn’t sign the auction protocol in 3 business days", 
    "title": "Disqualified"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "unsuccessful", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "bid_owner", 
        "title": "auction_protocol.pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/61f5777fa91e49079818ef3f117c362b?KeyID=172d32c8&Signature=MYxZ8Jxg41Lvt9ePuC18YYkaPrftRN2sdH0UDYrHuMC2jtyYKBLmPtxf%252BapAPgsR6qw9LVndR0yKbO0YpcUlDw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "auction", 
        "datePublished": "2018-12-07T19:32:45.605096+02:00", 
        "documentType": "auctionProtocol", 
        "dateModified": "2018-12-07T19:32:45.605115+02:00", 
        "id": "60f4968f2e21401c8ec01e3321208d79"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "auction_owner", 
        "title": "RejectionProtocol.pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/39e65d50ec2347649cbf1f42d42db41c?KeyID=172d32c8&Signature=MygIKX4t39lh2CMtjQnjvlwE3R38y2tLlyUNrr8i6%2Fd21%2FL1RqQQrBGXr4jvapxsLduun1Cbh4yUSZzjN58xDA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "auction", 
        "datePublished": "2018-12-07T19:32:45.701583+02:00", 
        "documentType": "rejectionProtocol", 
        "dateModified": "2018-12-07T19:32:45.701602+02:00", 
        "id": "8ac78d447af448f29e03a884b07ed4c8"
      }
    ], 
    "verificationPeriod": {
      "startDate": "2018-12-07T19:32:45.485659+02:00", 
      "endDate": "2018-12-07T19:32:45.820502+02:00"
    }, 
    "description": "Candidate didn’t sign the auction protocol in 3 business days", 
    "title": "Disqualified", 
    "suppliers": [
      {
        "additionalIdentifiers": [
          {
            "scheme": "UA-FIN", 
            "id": "А01 457213"
          }
        ], 
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "complaintPeriod": {
      "startDate": "2018-12-07T19:32:45.058461+02:00", 
      "endDate": "2018-12-07T19:32:45.820502+02:00"
    }, 
    "bid_id": "1ba70dadeec448d8aecb003eef0acaad", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-12-07T19:32:45.830042+02:00", 
    "id": "7fea1585f8ff49e88f750a9f89080ce2", 
    "signingPeriod": {
      "startDate": "2018-12-07T19:32:45.485659+02:00", 
      "endDate": "2019-01-16T18:00:00+02:00"
    }
  }
}

