PATCH /api/2.3/auctions/6f0f6b78d53f463bbd96a6e7721b15aa/awards/d1083268c50c4fa2b55c30351d57e1c1?acc_token=d04bcd5a5db84bebaf2d7af95aea2a4a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 146
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "unsuccessful", 
    "description": "Candidate didn’t sign the auction protocol in 3 business days", 
    "title": "Disqualified"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "unsuccessful", 
    "documents": [
      {
        "dateModified": "2018-03-13T17:49:00.542652+02:00", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/7ede9960779e46a0a2566d2f31dc2cd0?KeyID=3ad9481a&Signature=xxQKAL%252B3srRivLQgQzdsKhX2n4%252BLPsOkt6uYjHQMXjrrL%2FPMPP9iSKa3jQiu3CoRmz5thKn9Qco%2FVIccfnPNDw%253D%253D", 
        "author": "bid_owner", 
        "documentOf": "tender", 
        "datePublished": "2018-03-13T17:49:00.542631+02:00", 
        "documentType": "auctionProtocol", 
        "title": "auction_protocol.pdf", 
        "id": "ab622968b0944f7d94e2f7702da54c61"
      }, 
      {
        "dateModified": "2018-03-13T17:49:00.623811+02:00", 
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Disqualification reason", 
        "author": "auction_owner", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/719ad9fe39f744acb248bd2d32d9f9af?KeyID=3ad9481a&Signature=tjEu7V%2FxtrYA%252BNpAv6YB5Yje17vtaRGdbpxI71wYj08QHJCb3mYCbJARem%2FpkX%2FoC7SPp5mFNRCqRgT7m3GtBQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-03-13T17:49:00.623792+02:00", 
        "title": "Disqualified_reason.pdf", 
        "id": "a9e934f6aa8d4ed8be541d81c44feef0"
      }
    ], 
    "verificationPeriod": {
      "startDate": "2018-03-13T17:49:00.433838+02:00", 
      "endDate": "2018-03-13T17:49:00.719379+02:00"
    }, 
    "description": "Candidate didn’t sign the auction protocol in 3 business days", 
    "title": "Disqualified", 
    "suppliers": [
      {
        "additionalIdentifiers": [
          {
            "scheme": "UA-FIN", 
            "id": "А01 457213"
          }
        ], 
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "complaintPeriod": {
      "startDate": "2018-03-13T17:49:00.161595+02:00", 
      "endDate": "2018-03-13T17:49:00.719379+02:00"
    }, 
    "bid_id": "408137f98b17480cbd50c7d917d591fd", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-03-13T17:49:00.729111+02:00", 
    "id": "d1083268c50c4fa2b55c30351d57e1c1", 
    "signingPeriod": {
      "startDate": "2018-03-13T17:49:00.433838+02:00", 
      "endDate": "2018-03-13T18:09:00.058838+02:00"
    }
  }
}

