POST /api/2.5/auctions/17a42b23eaed4286a8937da1348817bb/awards/4e8136ff281a4f97aca77361f2e29641/documents?acc_token=b08a569f0fc244778d05c70166974957 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 377
Content-Type: application/json
Host: https://lb.api-sandbox.ea2.openprocurement.net/api/2.3/auctions
DATA:
{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/990c527a9fe34b218bcb6330691b6a3a?KeyID=172d32c8&Signature=iE%2F8ruakyL6beJiIgA2h8QaYgOyzRNYqkUxIVDtumj%2Bat2Zs9lrWAHl9XpPtYmAzsrm6ovTGQaf44wY6XHuWCg%3D%3D", 
    "title": "RejectionProtocol.pdf", 
    "format": "application/pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "documentType": "rejectionProtocol"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://https://lb.api-sandbox.ea2.openprocurement.net/api/2.3/auctions/api/2.5/auctions/17a42b23eaed4286a8937da1348817bb/awards/4e8136ff281a4f97aca77361f2e29641/documents/b743cbdfd1444110bfdf3740457ddff1
X-Content-Type-Options: nosniff
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "auction_owner", 
    "title": "RejectionProtocol.pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/990c527a9fe34b218bcb6330691b6a3a?KeyID=172d32c8&Signature=npfcCCOLpOyFNfnK9p0RC4z5%252BMbLIAozLJ4nOE0tw033hfeLUdS%252BFndF4MtD8MZPw86N%2FG79eG%2F62fpy54S9BQ%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "auction", 
    "datePublished": "2019-01-28T12:32:16.508364+02:00", 
    "documentType": "rejectionProtocol", 
    "dateModified": "2019-01-28T12:32:16.508385+02:00", 
    "id": "b743cbdfd1444110bfdf3740457ddff1"
  }
}

