PATCH /api/2.3/auctions/dea1897bef8e477799e5d6111f1f83b4/bids/11d5b0fcb829464cb0cbb082ebbc437a?acc_token=4f0b0503e2ea41609a1b0eabd288d190 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "eligible": true, 
    "date": "2017-09-27T15:00:47.616806+03:00", 
    "qualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "owner": "broker", 
    "id": "11d5b0fcb829464cb0cbb082ebbc437a", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/insider-auctions/dea1897bef8e477799e5d6111f1f83b4/login?bidder_id=11d5b0fcb829464cb0cbb082ebbc437a&signature=MhCroCffN8lHo7dSnDIJ%2BghDOuyO3lZJhRZyxqLvEcj3w6zLoSL2JnZK0Gmjv69Ter7IWfeTNKdes%2BERxIfgBg%3D%3D"
  }
}

