PATCH /api/2.5/auctions/e0c4d484a95140569171138086703f23/bids/f59572206a724c87901cfd00ff8244ff?acc_token=898cfa971bac42239310ee094fdb7b78 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: https://lb.api-sandbox.ea2.openprocurement.net/api/2.3/auctions
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "date": "2019-01-28T12:32:18.673849+02:00", 
    "qualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "owner": "broker", 
    "id": "f59572206a724c87901cfd00ff8244ff", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/insider-auctions/e0c4d484a95140569171138086703f23/login?bidder_id=f59572206a724c87901cfd00ff8244ff&signature=qlOLANfxG6AFyIZQ1OW4yMLNPZyNNexBKT5LicVdwBCqBICJyql4YvkHdQ8bI4qDhdqV61B/CRq7Xqc3DtXzDA%3D%3D"
  }
}

