POST /api/2.5/auctions/0a3e5825752c49199ced43de14247e09/documents?acc_token=2ae288c6a1204108bc3013241ac553eb HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 160
Content-Type: application/json
Host: lb.api-sandbox.registry.ea.openprocurement.net
DATA:
{
  "data": {
    "title": "Familiarization with bank asset", 
    "accessDetails": "Familiar with asset: days, time, address", 
    "documentType": "x_dgfAssetFamiliarization"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb.api-sandbox.registry.ea.openprocurement.net/api/2.5/auctions/0a3e5825752c49199ced43de14247e09/documents/8e4619deece5428b8527a40c8de0de52
X-Content-Type-Options: nosniff
{
  "data": {
    "title": "Familiarization with bank asset", 
    "format": "offline/on-site-examination", 
    "accessDetails": "Familiar with asset: days, time, address", 
    "documentOf": "tender", 
    "datePublished": "2018-12-07T19:32:46.964970+02:00", 
    "documentType": "x_dgfAssetFamiliarization", 
    "dateModified": "2018-12-07T19:32:46.964991+02:00", 
    "id": "8e4619deece5428b8527a40c8de0de52"
  }
}

