PATCH /api/2.5/auctions/0a3e5825752c49199ced43de14247e09/questions/1bbe17842ab4463cacb3386646914f1c?acc_token=2ae288c6a1204108bc3013241ac553eb HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 162
Content-Type: application/json
Host: lb.api-sandbox.registry.ea.openprocurement.net
DATA:
{
  "data": {
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\""
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "title": "Калорійність", 
    "date": "2018-12-07T19:32:47.052175+02:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "1bbe17842ab4463cacb3386646914f1c", 
    "questionOf": "tender"
  }
}

