POST /api/2.5/auctions/0a3e5825752c49199ced43de14247e09/questions HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1506
Content-Type: application/json
Host: lb.api-sandbox.registry.ea.openprocurement.net
DATA:
{
  "data": {
    "author": {
      "contactPoint": {
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк", 
        "email": "soleksuk@gmail.com"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "00137226", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "21100", 
        "region": "м. Вінниця", 
        "streetAddress": "вул. Островського, 33", 
        "locality": "м. Вінниця"
      }
    }, 
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "title": "Калорійність"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb.api-sandbox.registry.ea.openprocurement.net/api/2.5/auctions/0a3e5825752c49199ced43de14247e09/questions/1bbe17842ab4463cacb3386646914f1c
X-Content-Type-Options: nosniff
{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "uri": "http://sch10.edu.vn.ua/", 
        "id": "00137226"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Калорійність", 
    "date": "2018-12-07T19:32:47.052175+02:00", 
    "id": "1bbe17842ab4463cacb3386646914f1c", 
    "questionOf": "tender"
  }
}

