GET /api/2.5/auctions/e0c4d484a95140569171138086703f23/contracts/d76886a9843e4f808588f58574dcb6c9/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: https://lb.api-sandbox.ea2.openprocurement.net/api/2.3/auctions

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "title": "contract_first_document.doc", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/b7d0b588dd384a978d9ffb21449240f1?KeyID=172d32c8&Signature=LgYWwqGPjlhYsD53mpm8fhwedTGzfeLj0fi6TReADET4PMRZN4qnMRCAMnTnMVQnfNAVvLbWyJ4WvCq3XdWGCQ%253D%253D", 
      "format": "application/msword", 
      "documentOf": "auction", 
      "datePublished": "2019-01-28T12:32:21.096880+02:00", 
      "dateModified": "2019-01-28T12:32:21.096930+02:00", 
      "id": "bc2700d6e7fd485ea78e86cb23fbe9bf"
    }
  ]
}

