GET /api/2.5/auctions/0a3e5825752c49199ced43de14247e09/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb.api-sandbox.registry.ea.openprocurement.net

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "document description", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/cec2473dcf334f84a6eda4dd4f223b54?KeyID=172d32c8&Signature=vXiuThpgZnfDuei34UPauCckBdIIvbgf1PQwN3%2Fhtku0QtnmYZE%252BEDhG0dF5qWNTjbOL06QJBJxbimPxh2XSDg%253D%253D", 
      "title": "Notice.pdf", 
      "documentOf": "tender", 
      "datePublished": "2018-12-07T19:32:46.577230+02:00", 
      "documentType": "technicalSpecifications", 
      "dateModified": "2018-12-07T19:32:46.577251+02:00", 
      "id": "83124e21000e4fcbb2459ebdeed9d813"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/25fbbbe7a6e5459eb51b8f46cbd2b4bd?KeyID=172d32c8&Signature=O%252Bl5pUX65yElbq4o5A2E1gTpXBN4EihOth%252Bb3XseESkl57q9YkZQuovXwz27N5L0sWNB70TIaNeQUD0pa19zBg%253D%253D", 
      "title": "AwardCriteria-2.pdf", 
      "documentOf": "tender", 
      "datePublished": "2018-12-07T19:32:46.631127+02:00", 
      "dateModified": "2018-12-07T19:32:46.690425+02:00", 
      "id": "aeb0731d9d994d4e889efb74564aa0e1"
    }, 
    {
      "index": 1, 
      "hash": "md5:00000000000000000000000000000000", 
      "description": "First illustration description", 
      "format": "image/jpeg", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/86a31bfc90b146daada8bcaaea249fae?KeyID=172d32c8&Signature=v9rr8%2F2XvR3seMAi4OUguDPt7nvVwsuDxhtsyamgVhxbiCwR6q%2FsqwRqG8uoGzXgEQRJW%2Fx0%2FoLlJsIpJt0QBQ%253D%253D", 
      "title": "first_illustration.jpeg", 
      "documentOf": "tender", 
      "datePublished": "2018-12-07T19:32:46.749631+02:00", 
      "documentType": "illustration", 
      "dateModified": "2018-12-07T19:32:46.749652+02:00", 
      "id": "9fb85bc93fca46a2aa1249dcc332f91f"
    }, 
    {
      "index": 2, 
      "hash": "md5:00000000000000000000000000000000", 
      "description": "Second illustration description", 
      "format": "image/jpeg", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/717b626eca294ca683983c7357f8ac38?KeyID=172d32c8&Signature=rwjpcybLuSvPSPIBB%252Bzvu9BHKaaPDA7T1ztY55ZQSbDIJ9LJogTRYDJn%252B0VZ0EtS4PM482htRZzrOhiD4KheCg%253D%253D", 
      "title": "second_illustration.jpeg", 
      "documentOf": "tender", 
      "datePublished": "2018-12-07T19:32:46.823785+02:00", 
      "documentType": "illustration", 
      "dateModified": "2018-12-07T19:32:46.823805+02:00", 
      "id": "daf3e8d92dfa45dfb53b9e1642e7d536"
    }, 
    {
      "index": 2, 
      "hash": "md5:00000000000000000000000000000000", 
      "description": "Third illustration description", 
      "format": "image/jpeg", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/170853d3f13f4886832435402282bc23?KeyID=172d32c8&Signature=uC3%252BL3KgN9A42hXxQBrhPlLYT%252BdYey2%252BF4BNKFlbWaowXGlgodrRDkyG1ZQYDroD8Xc85Ybj0nhDqVHvw1QfBQ%253D%253D", 
      "title": "third_illustration.jpeg", 
      "documentOf": "tender", 
      "datePublished": "2018-12-07T19:32:46.884752+02:00", 
      "documentType": "illustration", 
      "dateModified": "2018-12-07T19:32:46.884775+02:00", 
      "id": "77f73be3f482443ba8bb5b7e8912fd09"
    }, 
    {
      "title": "Familiarization with bank asset", 
      "format": "offline/on-site-examination", 
      "accessDetails": "Familiar with asset: days, time, address", 
      "documentOf": "tender", 
      "datePublished": "2018-12-07T19:32:46.964970+02:00", 
      "documentType": "x_dgfAssetFamiliarization", 
      "dateModified": "2018-12-07T19:32:46.964991+02:00", 
      "id": "8e4619deece5428b8527a40c8de0de52"
    }
  ]
}

