PATCH /api/2.5/auctions/e0c4d484a95140569171138086703f23/contracts/d76886a9843e4f808588f58574dcb6c9?acc_token=4cc54038a92f4f578a435ca9cb041343 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 106
Content-Type: application/json
Host: https://lb.api-sandbox.ea2.openprocurement.net/api/2.3/auctions
DATA:
{
  "data": {
    "period": {
      "startDate": "2019-01-28T12:32:10.896560", 
      "endDate": "2020-01-28T12:32:10.896560"
    }
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "pending", 
    "signingPeriod": {
      "startDate": "2019-01-28T12:32:19.988125+02:00", 
      "endDate": "2019-02-18T18:00:00+02:00"
    }, 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CPV", 
          "description": "Земельні ділянки", 
          "id": "51413000-0"
        }, 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "46ff602897964fdeb334c4a55e9bc9d7", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "period": {
      "startDate": "2019-01-28T12:32:10.896560+02:00", 
      "endDate": "2020-01-28T12:32:10.896560+02:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 479, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-01-28T12:32:20.699137+02:00", 
    "awardID": "8e0279bc48cd41949e6ba8d436f31a0f", 
    "id": "d76886a9843e4f808588f58574dcb6c9", 
    "contractID": "UA-EA-2019-01-28-000002-1"
  }
}

