PATCH /api/2.3/auctions/ca31727f31f243b089cbc005b8fda5ba/contracts/30925f126c174b389a1eed392c9f0c9e?acc_token=0ce53b3a0d5d47778c36b80f90b81ad5 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 80
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "active", 
    "dateSigned": "2018-03-13T17:49:05.103318+02:00"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "prolongations": [
      {
        "status": "applied", 
        "decisionID": "ZM-937-99-92", 
        "description": "Prolongation description", 
        "datePublished": "2018-03-13T17:48:55.444916+02:00", 
        "reason": "other", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "format": "application/msword", 
            "url": "http://public.docs-sandbox.ea.openprocurement.org/get/bf938a820dfd4afea7f6257f6b7890c0?KeyID=9051732b&Signature=3lf7HJKApzjAFumRfN8w7KjWRD1YZFly%252BwEFyrOpiVrbc3m%2FKl%252BJq1X%252BJuEXRkkDwzc1nTgA0GtXovI2Gjr3Cg%253D%253D", 
            "title": "ProlongationDocument.doc", 
            "documentOf": "tender", 
            "datePublished": "2018-03-13T17:49:04.483038+02:00", 
            "documentType": "prolongationProtocol", 
            "dateModified": "2018-03-13T17:49:04.483060+02:00", 
            "id": "876f84e9cb9e4c78bc59a82f6a994aa7"
          }
        ], 
        "dateCreated": "2018-03-13T17:48:56.056522+02:00", 
        "id": "5a7332f6287f4f36ab23e2f00b755a5b"
      }, 
      {
        "status": "applied", 
        "decisionID": "ZM-937-99-92-2", 
        "description": "Long prolongation description", 
        "datePublished": "2018-03-13T17:48:55.444945+02:00", 
        "reason": "other", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "format": "application/msword", 
            "url": "http://public.docs-sandbox.ea.openprocurement.org/get/83bf8a28d4b54833b5050aa186d5dafc?KeyID=9051732b&Signature=hEOASma%2FODQf7xlDG%2FXkEYDkNskZT7o8wdNu7a0mAzDIEpRnvTOHYIwRwggMdVjnVsszxyiTE4Oa1q%252BPTG8lAQ%253D%253D", 
            "title": "LongProlongationDocument.doc", 
            "documentOf": "tender", 
            "datePublished": "2018-03-13T17:49:04.872779+02:00", 
            "documentType": "prolongationProtocol", 
            "dateModified": "2018-03-13T17:49:04.872805+02:00", 
            "id": "3ac38b03ea5147c2bb4b5b7aa432ea56"
          }
        ], 
        "dateCreated": "2018-03-13T17:48:56.056522+02:00", 
        "id": "17001a57deec4c9e8d94893e98a41b2c"
      }
    ], 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/39b2454289e240d38e00636e2e79016a?KeyID=9051732b&Signature=sGiPfaDjXW6iDJHcCpbc1eAc6aGcy9NdEnxZLrLVxcpIIbLp2TheHdUM4klGIrfd7L8rbhBG83PEk%252BrW9%252BzCCg%253D%253D", 
        "title": "contract_first_document.doc", 
        "documentOf": "tender", 
        "datePublished": "2018-03-13T17:49:03.945461+02:00", 
        "documentType": "prolongationProtocol", 
        "dateModified": "2018-03-13T17:49:03.945487+02:00", 
        "id": "393a04982b1441138438c7273b49eac1"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/88721cf4cae843ee80ce612a2fe1b79b?KeyID=9051732b&Signature=ZA%2FjEQr6RDA%2F7FhI6UstyyAqrqKmIsxU4EyuYfLUVSu8Wj3BPm3E3ypVkeG3dVLIhZm785Un8%2Fr4ZM%252BvC8F0AQ%253D%253D", 
        "title": "contract_second_document.doc", 
        "documentOf": "tender", 
        "datePublished": "2018-03-13T17:49:04.104741+02:00", 
        "documentType": "prolongationProtocol", 
        "dateModified": "2018-03-13T17:49:04.104761+02:00", 
        "id": "718396f63ab84e5d805f02e0026c9ded"
      }
    ], 
    "signingPeriod": {
      "startDate": "2018-03-13T17:49:03.167518+02:00", 
      "endDate": "2018-07-23T17:49:03.167518+02:00"
    }, 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV", 
          "description": "Земельні ділянки", 
          "id": "06000000-2"
        }, 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "e24b924ada114a0d95d03a8c89eadda7", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "period": {
      "startDate": "2018-03-13T17:48:55.444611+02:00", 
      "endDate": "2019-03-13T17:48:55.444611+02:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 479.0, 
      "valueAddedTaxIncluded": true
    }, 
    "dateSigned": "2018-03-13T17:49:05.103318+02:00", 
    "date": "2018-03-13T17:49:05.192504+02:00", 
    "awardID": "7d4e36e2232f45b0910f887feaf23af1", 
    "id": "30925f126c174b389a1eed392c9f0c9e", 
    "contractID": "UA-EA-2018-03-13-000001-1"
  }
}

