GET /api/2.5/auctions/e0c4d484a95140569171138086703f23/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: https://lb.api-sandbox.ea2.openprocurement.net/api/2.3/auctions

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "document description", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/6ac51cb148a042db8c3ff05ca03e17eb?KeyID=172d32c8&Signature=ODek9PjlhbCkmeL80dDgAiaDHzTqYEmQSYBqYnKfyIFMJoQsrLkzcPHkb3Cnpj%2FYCHink%252B2Hl6ag%252BbdlGkv1DA%253D%253D", 
      "title": "Notice.pdf", 
      "documentOf": "auction", 
      "datePublished": "2019-01-28T12:32:17.643280+02:00", 
      "documentType": "technicalSpecifications", 
      "dateModified": "2019-01-28T12:32:17.643302+02:00", 
      "id": "c33444fdcca243b382630e9924d54509"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "title": "AwardCriteria-2.pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/53ef485f1a1f41b6a6fbad631572346c?KeyID=172d32c8&Signature=zS2ipM2G7i8Y%252BpT9XNBXW2Hi9LM4x8w40wpyHXaZJRCymcX5BJLEELPBgK8SDWqB22j8DvskE1XSa75hh7n3Dg%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "auction", 
      "datePublished": "2019-01-28T12:32:17.724608+02:00", 
      "dateModified": "2019-01-28T12:32:17.817955+02:00", 
      "id": "b85a9b4422084bd49a2885b32fe9b4b9"
    }, 
    {
      "index": 1, 
      "hash": "md5:00000000000000000000000000000000", 
      "description": "First illustration description", 
      "format": "image/jpeg", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/c82312f5185f4134ad73697a076eb077?KeyID=172d32c8&Signature=TGH4gd2rROfKB3wsnIwhIfPMu45Caqv2EG3yjy5NJl1C12z1wf1XcfvsavyA%2F7pnWqRX3Eo%252BTUqSn69pPiiiCQ%253D%253D", 
      "title": "first_illustration.jpeg", 
      "documentOf": "auction", 
      "datePublished": "2019-01-28T12:32:17.924605+02:00", 
      "documentType": "illustration", 
      "dateModified": "2019-01-28T12:32:17.924642+02:00", 
      "id": "44c7331c169b47f6aea97b05846b0d74"
    }, 
    {
      "index": 2, 
      "hash": "md5:00000000000000000000000000000000", 
      "description": "Second illustration description", 
      "format": "image/jpeg", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/8581590c05844a9c8d527b63232aff4a?KeyID=172d32c8&Signature=4lr0rXnd1icb0cmt9itu1y2c1OWAZrI3nyi8JYtfY6llpSryb2sVvlV6HgGDJiJTYA4yW7OqXmMZXwZuzArxDA%253D%253D", 
      "title": "second_illustration.jpeg", 
      "documentOf": "auction", 
      "datePublished": "2019-01-28T12:32:18.049118+02:00", 
      "documentType": "illustration", 
      "dateModified": "2019-01-28T12:32:18.049168+02:00", 
      "id": "84bace22f9114d8d98f2c9c06a858c6d"
    }, 
    {
      "index": 2, 
      "hash": "md5:00000000000000000000000000000000", 
      "description": "Third illustration description", 
      "format": "image/jpeg", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/175b11887c4d48498b9aa02d194ed679?KeyID=172d32c8&Signature=TOp%252BFcDvaNPDgm%2Fl%252BznQuaqJRM7qjfxV4EvgmHIfM9fXyJjyneOu9k%252B28BNJn0qA3FEGFzDyHONIx8msSzlvDw%253D%253D", 
      "title": "third_illustration.jpeg", 
      "documentOf": "auction", 
      "datePublished": "2019-01-28T12:32:18.139983+02:00", 
      "documentType": "illustration", 
      "dateModified": "2019-01-28T12:32:18.140007+02:00", 
      "id": "2e87d27713dd488ab403104d6b41b338"
    }, 
    {
      "title": "Familiarization with bank asset", 
      "format": "offline/on-site-examination", 
      "accessDetails": "Familiar with asset: days, time, address", 
      "documentOf": "auction", 
      "datePublished": "2019-01-28T12:32:18.267862+02:00", 
      "documentType": "x_dgfAssetFamiliarization", 
      "dateModified": "2019-01-28T12:32:18.267912+02:00", 
      "id": "70f92e8fa46046e3955bab0701ffedf1"
    }
  ]
}

