POST /api/2.5/auctions/0a3e5825752c49199ced43de14247e09/contracts/52c8c00a6cbb4c23b9cba3a049f90bce/documents?acc_token=2ae288c6a1204108bc3013241ac553eb HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 351
Content-Type: application/json
Host: lb.api-sandbox.registry.ea.openprocurement.net
DATA:
{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/192d63d4ee8c4e5783ba864437e16811?KeyID=172d32c8&Signature=1LP8EOUhg8HNlWNRSJknrv1vrEGb8LfYGD3Rt1hkGs5OS7gu%2FhT8l9R9%2BqgOORXZRY0%2BOBwWUR1zMA6Ze4ARDg%3D%3D", 
    "title": "contract_first_document.doc", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/msword"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb.api-sandbox.registry.ea.openprocurement.net/api/2.5/auctions/0a3e5825752c49199ced43de14247e09/contracts/52c8c00a6cbb4c23b9cba3a049f90bce/documents/0fa184d9b85c48afa58dd0b158137147
X-Content-Type-Options: nosniff
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "title": "contract_first_document.doc", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/192d63d4ee8c4e5783ba864437e16811?KeyID=172d32c8&Signature=AfFKO8OjjV6cc148At93UUUsnQON3Qkn5uU%252B1EFiNiaRDy2662PdFJIR%252BLxLK4ksoTtYMdDeJcoHNL2HNWxXCg%253D%253D", 
    "format": "application/msword", 
    "documentOf": "auction", 
    "datePublished": "2018-12-07T19:32:48.821086+02:00", 
    "dateModified": "2018-12-07T19:32:48.821108+02:00", 
    "id": "0fa184d9b85c48afa58dd0b158137147"
  }
}

