GET /api/2.5/auctions/0a3e5825752c49199ced43de14247e09 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb.api-sandbox.registry.ea.openprocurement.net

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2018-12-07-000002", 
    "auctionUrl": "http://auction-sandbox.openprocurement.org/insider-auctions/0a3e5825752c49199ced43de14247e09", 
    "enquiryPeriod": {
      "startDate": "2018-11-17T19:32:42.120568+02:00", 
      "endDate": "2018-12-07T19:32:42.120568+02:00"
    }, 
    "registrationFee": {
      "currency": "UAH", 
      "amount": 700.87
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2018-12-08T02:48:32.120568+02:00", 
    "awardCriteria": "highestCost", 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "title": "Калорійність", 
        "date": "2018-12-07T19:32:47.052175+02:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "1bbe17842ab4463cacb3386646914f1c", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "id": "0a3e5825752c49199ced43de14247e09", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "document description", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/cec2473dcf334f84a6eda4dd4f223b54?KeyID=172d32c8&Signature=vXiuThpgZnfDuei34UPauCckBdIIvbgf1PQwN3%2Fhtku0QtnmYZE%252BEDhG0dF5qWNTjbOL06QJBJxbimPxh2XSDg%253D%253D", 
        "title": "Notice.pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-12-07T19:32:46.577230+02:00", 
        "documentType": "technicalSpecifications", 
        "dateModified": "2018-12-07T19:32:46.577251+02:00", 
        "id": "83124e21000e4fcbb2459ebdeed9d813"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/281d783c1b6346e780f9f9dab1dcf430?KeyID=172d32c8&Signature=KFMZBRs5MRqjPYqfG4PJdpRFN4%2FQ8Al4M4vhs0Ao2hiezyi%2FHw3%2Fg3A8tic4SFhOdiwBAT2z%252BE6cOTeh4uiaCw%253D%253D", 
        "title": "AwardCriteria.pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-12-07T19:32:46.631127+02:00", 
        "dateModified": "2018-12-07T19:32:46.631149+02:00", 
        "id": "aeb0731d9d994d4e889efb74564aa0e1"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/25fbbbe7a6e5459eb51b8f46cbd2b4bd?KeyID=172d32c8&Signature=O%252Bl5pUX65yElbq4o5A2E1gTpXBN4EihOth%252Bb3XseESkl57q9YkZQuovXwz27N5L0sWNB70TIaNeQUD0pa19zBg%253D%253D", 
        "title": "AwardCriteria-2.pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-12-07T19:32:46.631127+02:00", 
        "dateModified": "2018-12-07T19:32:46.690425+02:00", 
        "id": "aeb0731d9d994d4e889efb74564aa0e1"
      }, 
      {
        "index": 1, 
        "hash": "md5:00000000000000000000000000000000", 
        "description": "First illustration description", 
        "format": "image/jpeg", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/86a31bfc90b146daada8bcaaea249fae?KeyID=172d32c8&Signature=v9rr8%2F2XvR3seMAi4OUguDPt7nvVwsuDxhtsyamgVhxbiCwR6q%2FsqwRqG8uoGzXgEQRJW%2Fx0%2FoLlJsIpJt0QBQ%253D%253D", 
        "title": "first_illustration.jpeg", 
        "documentOf": "tender", 
        "datePublished": "2018-12-07T19:32:46.749631+02:00", 
        "documentType": "illustration", 
        "dateModified": "2018-12-07T19:32:46.749652+02:00", 
        "id": "9fb85bc93fca46a2aa1249dcc332f91f"
      }, 
      {
        "index": 2, 
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Second illustration description", 
        "format": "image/jpeg", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/717b626eca294ca683983c7357f8ac38?KeyID=172d32c8&Signature=rwjpcybLuSvPSPIBB%252Bzvu9BHKaaPDA7T1ztY55ZQSbDIJ9LJogTRYDJn%252B0VZ0EtS4PM482htRZzrOhiD4KheCg%253D%253D", 
        "title": "second_illustration.jpeg", 
        "documentOf": "tender", 
        "datePublished": "2018-12-07T19:32:46.823785+02:00", 
        "documentType": "illustration", 
        "dateModified": "2018-12-07T19:32:46.823805+02:00", 
        "id": "daf3e8d92dfa45dfb53b9e1642e7d536"
      }, 
      {
        "index": 2, 
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Third illustration description", 
        "format": "image/jpeg", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/170853d3f13f4886832435402282bc23?KeyID=172d32c8&Signature=uC3%252BL3KgN9A42hXxQBrhPlLYT%252BdYey2%252BF4BNKFlbWaowXGlgodrRDkyG1ZQYDroD8Xc85Ybj0nhDqVHvw1QfBQ%253D%253D", 
        "title": "third_illustration.jpeg", 
        "documentOf": "tender", 
        "datePublished": "2018-12-07T19:32:46.884752+02:00", 
        "documentType": "illustration", 
        "dateModified": "2018-12-07T19:32:46.884775+02:00", 
        "id": "77f73be3f482443ba8bb5b7e8912fd09"
      }, 
      {
        "title": "Familiarization with bank asset", 
        "format": "offline/on-site-examination", 
        "accessDetails": "Familiar with asset: days, time, address", 
        "documentOf": "tender", 
        "datePublished": "2018-12-07T19:32:46.964970+02:00", 
        "documentType": "x_dgfAssetFamiliarization", 
        "dateModified": "2018-12-07T19:32:46.964991+02:00", 
        "id": "8e4619deece5428b8527a40c8de0de52"
      }
    ], 
    "title": "футляри до державних нагород", 
    "tenderAttempts": 1, 
    "auctionParameters": {
      "type": "insider", 
      "dutchSteps": 88
    }, 
    "dateModified": "2018-12-07T19:32:47.692042+02:00", 
    "status": "active.auction", 
    "tenderPeriod": {
      "startDate": "2018-11-17T19:32:42.120568+02:00", 
      "endDate": "2018-12-08T02:17:42.120568+02:00"
    }, 
    "auctionPeriod": {
      "startDate": "2018-12-07T19:32:42.120568+02:00", 
      "shouldStartAfter": "2018-12-08T00:00:00+02:00"
    }, 
    "bankAccount": {
      "accountIdentification": [
        {
          "scheme": "accountNumber", 
          "id": "111111-8", 
          "description": "some description"
        }
      ], 
      "bankName": "name of bank"
    }, 
    "procurementMethodType": "appraisal.insider", 
    "date": "2018-12-07T19:32:47.692042+02:00", 
    "lotIdentifier": "Q24421K222", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CPV", 
          "description": "Земельні ділянки", 
          "id": "51413000-0"
        }, 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "6c318ef0d2954b0480d3310fe83d9266", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }
  }
}

