POST /api/2.5/auctions?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2333
Content-Type: application/json
Host: lb.api-sandbox.registry.ea.openprocurement.net
DATA:
{
  "data": {
    "bankAccount": {
      "accountIdentification": [
        {
          "scheme": "accountNumber", 
          "id": "111111-8", 
          "description": "some description"
        }
      ], 
      "bankName": "name of bank"
    }, 
    "lotIdentifier": "Q24421K222", 
    "documents": [
      {
        "format": "application/msword", 
        "title": "укр.doc", 
        "accessDetails": "access details", 
        "documentType": "x_dgfAssetFamiliarization"
      }
    ], 
    "title": "футляри до державних нагород", 
    "auctionPeriod": {
      "startDate": "2018-12-21"
    }, 
    "tenderAttempts": 1, 
    "procurementMethodType": "appraisal.insider", 
    "value": {
      "currency": "UAH", 
      "amount": 100
    }, 
    "status": "draft", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }, 
    "items": [
      {
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова 1", 
          "locality": "м. Київ"
        }, 
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CPV", 
          "id": "51413000-0", 
          "description": "Земельні ділянки"
        }, 
        "quantity": 5
      }
    ], 
    "auctionParameters": {
      "type": "insider", 
      "dutchSteps": 88
    }, 
    "registrationFee": {
      "currency": "UAH", 
      "amount": 700.87
    }
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb.api-sandbox.registry.ea.openprocurement.net/api/2.5/auctions/0244c16ada084873b4ca06c655a53a88
X-Content-Type-Options: nosniff
{
  "access": {
    "transfer": "acea843b2aed41249388c46cca82194e", 
    "token": "33167dc7def04183a38a56cd16f3bbcc"
  }, 
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2018-12-07-000002", 
    "enquiryPeriod": {
      "startDate": "2018-12-07T19:32:43.743197+02:00", 
      "endDate": "2018-12-20T20:00:00+02:00"
    }, 
    "registrationFee": {
      "currency": "UAH", 
      "amount": 700.87
    }, 
    "submissionMethod": "electronicAuction", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "owner": "broker", 
    "id": "0244c16ada084873b4ca06c655a53a88", 
    "title": "футляри до державних нагород", 
    "tenderAttempts": 1, 
    "auctionParameters": {
      "type": "insider", 
      "dutchSteps": 88
    }, 
    "dateModified": "2018-12-07T19:32:43.764311+02:00", 
    "status": "draft", 
    "tenderPeriod": {
      "startDate": "2018-12-07T19:32:43.743197+02:00", 
      "endDate": "2018-12-21T16:15:00+02:00"
    }, 
    "bankAccount": {
      "accountIdentification": [
        {
          "scheme": "accountNumber", 
          "id": "111111-8", 
          "description": "some description"
        }
      ], 
      "bankName": "name of bank"
    }, 
    "procurementMethodType": "appraisal.insider", 
    "date": "2018-12-07T19:32:43.743197+02:00", 
    "lotIdentifier": "Q24421K222", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CPV", 
          "description": "Земельні ділянки", 
          "id": "51413000-0"
        }, 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "97d99debb55c48ebbcaf19b8984a0e18", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "highestCost"
  }
}

