POST /api/2.5/auctions?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2541
Content-Type: application/json
Host: https://lb.api-sandbox.ea2.openprocurement.net/api/2.3/auctions
DATA:
{
  "data": {
    "bankAccount": {
      "accountIdentification": [
        {
          "scheme": "accountNumber", 
          "id": "111111-8", 
          "description": "some description"
        }
      ], 
      "bankName": "name of bank"
    }, 
    "lotIdentifier": "Q24421K222", 
    "documents": [
      {
        "format": "application/msword", 
        "title": "укр.doc", 
        "accessDetails": "access details", 
        "documentType": "x_dgfAssetFamiliarization"
      }
    ], 
    "description": "description of appraisal auction", 
    "title": "футляри до державних нагород", 
    "submissionMethodDetails": "quick", 
    "auctionPeriod": {
      "startDate": "2019-01-28T12:37:10.896560"
    }, 
    "tenderAttempts": 1, 
    "procurementMethodType": "appraisal.insider", 
    "value": {
      "currency": "UAH", 
      "amount": 100
    }, 
    "guarantee": {
      "currency": "UAH", 
      "amount": 1000.99
    }, 
    "mode": "test", 
    "procurementMethodDetails": "quick, accelerator=1440", 
    "auctionParameters": {
      "type": "insider", 
      "dutchSteps": 88
    }, 
    "items": [
      {
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова 1", 
          "locality": "м. Київ"
        }, 
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CPV", 
          "id": "51413000-0", 
          "description": "Земельні ділянки"
        }, 
        "quantity": 5
      }
    ], 
    "registrationFee": {
      "currency": "UAH", 
      "amount": 700.87
    }, 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://https://lb.api-sandbox.ea2.openprocurement.net/api/2.3/auctions/api/2.5/auctions/a1160b54ee7a48d499562af4a31fdf1f
X-Content-Type-Options: nosniff
{
  "access": {
    "transfer": "d197f5adc19b4448a1e241f7bd0802ba", 
    "token": "be9ea0d391d94d0faa53a4bba41e3908"
  }, 
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2019-01-28-000002", 
    "enquiryPeriod": {
      "startDate": "2019-01-28T12:32:14.272562+02:00", 
      "endDate": "2019-01-28T12:36:29.347326+02:00"
    }, 
    "registrationFee": {
      "currency": "UAH", 
      "amount": 700.87
    }, 
    "submissionMethod": "electronicAuction", 
    "awardCriteria": "highestCost", 
    "owner": "broker", 
    "title_en": "[TESTING] ", 
    "id": "a1160b54ee7a48d499562af4a31fdf1f", 
    "description": "description of appraisal auction", 
    "title": "[ТЕСТУВАННЯ] футляри до державних нагород", 
    "tenderAttempts": 1, 
    "auctionParameters": {
      "type": "insider", 
      "dutchSteps": 88
    }, 
    "guarantee": {
      "currency": "UAH", 
      "amount": 1000.99
    }, 
    "dateModified": "2019-01-28T12:32:14.291361+02:00", 
    "status": "draft", 
    "tenderPeriod": {
      "startDate": "2019-01-28T12:32:14.272562+02:00", 
      "endDate": "2019-01-28T12:46:29.347326+02:00"
    }, 
    "procurementMethodDetails": "quick, accelerator=1440", 
    "bankAccount": {
      "accountIdentification": [
        {
          "scheme": "accountNumber", 
          "id": "111111-8", 
          "description": "some description"
        }
      ], 
      "bankName": "name of bank"
    }, 
    "procurementMethodType": "appraisal.insider", 
    "date": "2019-01-28T12:32:14.272562+02:00", 
    "lotIdentifier": "Q24421K222", 
    "rectificationPeriod": {
      "startDate": "2019-01-28T12:32:14.272562+02:00", 
      "endDate": "2019-01-28T12:41:29.347326+02:00"
    }, 
    "submissionMethodDetails": "quick", 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CPV", 
          "description": "Земельні ділянки", 
          "id": "51413000-0"
        }, 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "b303d615b75c4bed9bc4210bc4491c87", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 0, 
      "valueAddedTaxIncluded": true
    }, 
    "mode": "test", 
    "title_ru": "[ТЕСТИРОВАНИЕ] ", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }
  }
}

