GET /api/2.5/auctions/0a3e5825752c49199ced43de14247e09/contracts/52c8c00a6cbb4c23b9cba3a049f90bce/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb.api-sandbox.registry.ea.openprocurement.net

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "title": "contract_first_document.doc", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/192d63d4ee8c4e5783ba864437e16811?KeyID=172d32c8&Signature=AfFKO8OjjV6cc148At93UUUsnQON3Qkn5uU%252B1EFiNiaRDy2662PdFJIR%252BLxLK4ksoTtYMdDeJcoHNL2HNWxXCg%253D%253D", 
      "format": "application/msword", 
      "documentOf": "auction", 
      "datePublished": "2018-12-07T19:32:48.821086+02:00", 
      "dateModified": "2018-12-07T19:32:48.821108+02:00", 
      "id": "0fa184d9b85c48afa58dd0b158137147"
    }
  ]
}

