POST /api/2.5/auctions?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2434
Content-Type: application/json
Host: https://lb.api-sandbox.ea2.openprocurement.net/api/2.3/auctions
DATA:
{
  "data": {
    "bankAccount": {
      "accountIdentification": [
        {
          "scheme": "accountNumber", 
          "id": "111111-8", 
          "description": "some description"
        }
      ], 
      "bankName": "name of bank"
    }, 
    "lotIdentifier": "Q24421K222", 
    "documents": [
      {
        "format": "application/msword", 
        "title": "укр.doc", 
        "accessDetails": "access details", 
        "documentType": "x_dgfAssetFamiliarization"
      }
    ], 
    "description": "description of appraisal auction", 
    "title": "футляри до державних нагород", 
    "auctionPeriod": {
      "startDate": "2019-02-07T12:32:10.895130"
    }, 
    "tenderAttempts": 1, 
    "procurementMethodType": "appraisal.insider", 
    "value": {
      "currency": "UAH", 
      "amount": 100
    }, 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }, 
    "items": [
      {
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова 1", 
          "locality": "м. Київ"
        }, 
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CPV", 
          "id": "51413000-0", 
          "description": "Земельні ділянки"
        }, 
        "quantity": 5
      }
    ], 
    "auctionParameters": {
      "type": "insider", 
      "dutchSteps": 88
    }, 
    "registrationFee": {
      "currency": "UAH", 
      "amount": 700.87
    }, 
    "guarantee": {
      "currency": "UAH", 
      "amount": 1000.99
    }
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://https://lb.api-sandbox.ea2.openprocurement.net/api/2.3/auctions/api/2.5/auctions/e0c4d484a95140569171138086703f23
X-Content-Type-Options: nosniff
{
  "access": {
    "transfer": "bedb1a0ffdea449aad05c8cdf0f8c6be", 
    "token": "4cc54038a92f4f578a435ca9cb041343"
  }, 
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2019-01-28-000002", 
    "enquiryPeriod": {
      "startDate": "2019-01-28T12:32:17.146983+02:00", 
      "endDate": "2019-02-06T20:00:00+02:00"
    }, 
    "registrationFee": {
      "currency": "UAH", 
      "amount": 700.87
    }, 
    "submissionMethod": "electronicAuction", 
    "awardCriteria": "highestCost", 
    "owner": "broker", 
    "id": "e0c4d484a95140569171138086703f23", 
    "description": "description of appraisal auction", 
    "title": "футляри до державних нагород", 
    "tenderAttempts": 1, 
    "auctionParameters": {
      "type": "insider", 
      "dutchSteps": 88
    }, 
    "guarantee": {
      "currency": "UAH", 
      "amount": 1000.99
    }, 
    "dateModified": "2019-01-28T12:32:17.168827+02:00", 
    "status": "draft", 
    "tenderPeriod": {
      "startDate": "2019-01-28T12:32:17.146983+02:00", 
      "endDate": "2019-02-07T16:15:00+02:00"
    }, 
    "bankAccount": {
      "accountIdentification": [
        {
          "scheme": "accountNumber", 
          "id": "111111-8", 
          "description": "some description"
        }
      ], 
      "bankName": "name of bank"
    }, 
    "procurementMethodType": "appraisal.insider", 
    "date": "2019-01-28T12:32:17.146983+02:00", 
    "lotIdentifier": "Q24421K222", 
    "rectificationPeriod": {
      "startDate": "2019-01-28T12:32:17.146983+02:00", 
      "endDate": "2019-01-31T16:15:00+02:00"
    }, 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CPV", 
          "description": "Земельні ділянки", 
          "id": "51413000-0"
        }, 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "46ff602897964fdeb334c4a55e9bc9d7", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }
  }
}

