GET /api/2.3/auctions/ca31727f31f243b089cbc005b8fda5ba/contracts/30925f126c174b389a1eed392c9f0c9e/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/msword", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/39b2454289e240d38e00636e2e79016a?KeyID=9051732b&Signature=sGiPfaDjXW6iDJHcCpbc1eAc6aGcy9NdEnxZLrLVxcpIIbLp2TheHdUM4klGIrfd7L8rbhBG83PEk%252BrW9%252BzCCg%253D%253D", 
      "title": "contract_first_document.doc", 
      "documentOf": "tender", 
      "datePublished": "2018-03-13T17:49:03.945461+02:00", 
      "documentType": "prolongationProtocol", 
      "dateModified": "2018-03-13T17:49:03.945487+02:00", 
      "id": "393a04982b1441138438c7273b49eac1"
    }
  ]
}

