GET /api/2.5/auctions/0a3e5825752c49199ced43de14247e09/bids/16331e49f073425798ea4f18f3590c95?acc_token=72db756788834611b45a27690fa30121 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb.api-sandbox.registry.ea.openprocurement.net

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://lb.api-sandbox.registry.ea.openprocurement.net/api/2.5/auctions/0a3e5825752c49199ced43de14247e09/bids/16331e49f073425798ea4f18f3590c95/documents/0201da15b7944eae82633d7ea11c02e8?download=4b1b201c1f8a4730b47cc51339ed73b6", 
        "title": "Proposal.pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-12-07T19:32:47.381415+02:00", 
        "dateModified": "2018-12-07T19:32:47.381436+02:00", 
        "id": "0201da15b7944eae82633d7ea11c02e8"
      }
    ], 
    "eligible": true, 
    "date": "2018-12-07T19:32:47.242401+02:00", 
    "qualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "owner": "broker", 
    "id": "16331e49f073425798ea4f18f3590c95", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/insider-auctions/0a3e5825752c49199ced43de14247e09/login?bidder_id=16331e49f073425798ea4f18f3590c95&signature=vatRL%2BMAjtLyjJNv34jZn8wZZmLAlJlPJSUuDCIbdqvUOXLssSZW9j9upKHRTRyV68YLF%2BX5YSbjijINhvoeBg%3D%3D"
  }
}

