POST /api/2.5/auctions/e0c4d484a95140569171138086703f23/awards/8e0279bc48cd41949e6ba8d436f31a0f/documents?acc_token=40b7cd7fd2b4441396c1efa92bfc2b1b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 381
Content-Type: application/json
Host: https://lb.api-sandbox.ea2.openprocurement.net/api/2.3/auctions
DATA:
{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/733e3efd60604f2c8c2e2142fca2f269?KeyID=172d32c8&Signature=zORh6NIwF4bOKmcQss5VZgna8%2B1r%2FunOE3NKB42km3MExo3f3N5L391aAoWePu6%2Fwq4MKG3ZFzDYP2uPcL6vAw%3D%3D", 
    "title": "SignedAuctionProtocol.pdf", 
    "format": "application/pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "documentType": "auctionProtocol"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://https://lb.api-sandbox.ea2.openprocurement.net/api/2.3/auctions/api/2.5/auctions/e0c4d484a95140569171138086703f23/awards/8e0279bc48cd41949e6ba8d436f31a0f/documents/c15f1049d5c84aeaa164e4bb650daa0f
X-Content-Type-Options: nosniff
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "bid_owner", 
    "title": "SignedAuctionProtocol.pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/733e3efd60604f2c8c2e2142fca2f269?KeyID=172d32c8&Signature=aof6f%252BRhjahdFxYpQm%2Fc8bJxVu0TLoPAWVrMptbcSVoWiIGRObTlVDvelXFarRhIkCrZsp9laoSOA%252BYN8c%2FrDQ%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "auction", 
    "datePublished": "2019-01-28T12:32:20.409366+02:00", 
    "documentType": "auctionProtocol", 
    "dateModified": "2019-01-28T12:32:20.409386+02:00", 
    "id": "c15f1049d5c84aeaa164e4bb650daa0f"
  }
}

