POST /api/2.3/auctions/ca31727f31f243b089cbc005b8fda5ba/awards/7d4e36e2232f45b0910f887feaf23af1/documents?acc_token=0f09820ab05d457cac54e061ee8b9b2a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 377
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/a896d2bee21d48669b866b658a2b5421?KeyID=9051732b&Signature=7Gbk0xPVvAhPC0AqX08PCu9LBQXtExeYCnSfMBx1xShbXE2xBhI9QPAjYC2a%2BFi410oWlJYn4UqwK1q3nOp7DQ%3D%3D", 
    "title": "SignedAuctionProtocol.pdf", 
    "format": "application/pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "documentType": "auctionProtocol"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/ca31727f31f243b089cbc005b8fda5ba/awards/7d4e36e2232f45b0910f887feaf23af1/documents/dc7ccdfb41a44533a03a9cffff4a8850

{
  "data": {
    "dateModified": "2018-03-13T17:49:03.449222+02:00", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/a896d2bee21d48669b866b658a2b5421?KeyID=9051732b&Signature=i6P59QQMzh8%252BfWJik6jodxWwsAdokeAWTfJbaM76B5amghHYoZqUgrQxx%252BUU3WDT9Tr5cxxwrps4%2FZixJDgFDw%253D%253D", 
    "author": "bid_owner", 
    "documentOf": "tender", 
    "datePublished": "2018-03-13T17:49:03.449202+02:00", 
    "documentType": "auctionProtocol", 
    "title": "SignedAuctionProtocol.pdf", 
    "id": "dc7ccdfb41a44533a03a9cffff4a8850"
  }
}

