GET /api/2.5/auctions/e0c4d484a95140569171138086703f23/bids/a22200d873de40e39f7f4ab5dd59f7eb?acc_token=40b7cd7fd2b4441396c1efa92bfc2b1b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: https://lb.api-sandbox.ea2.openprocurement.net/api/2.3/auctions

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "date": "2019-01-28T12:32:19.091300+02:00", 
    "qualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "owner": "broker", 
    "id": "a22200d873de40e39f7f4ab5dd59f7eb", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/insider-auctions/e0c4d484a95140569171138086703f23/login?bidder_id=a22200d873de40e39f7f4ab5dd59f7eb&signature=PVInewnhc5/KpOU5TwAeWEu3yUmtGNJt1NUINQgyQ%2Bqnmjs7emZvnCx8KcsfL2eVAH5MtNNDxCQYPPL5HZTsAw%3D%3D"
  }
}

