GET /api/2.5/auctions/0a3e5825752c49199ced43de14247e09/bids/917fb2cdbacd4536ba64aeca993f8f53?acc_token=6cd7aafceb2046dda46579f952f05e05 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb.api-sandbox.registry.ea.openprocurement.net

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "date": "2018-12-07T19:32:47.484789+02:00", 
    "qualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "owner": "broker", 
    "id": "917fb2cdbacd4536ba64aeca993f8f53", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/insider-auctions/0a3e5825752c49199ced43de14247e09/login?bidder_id=917fb2cdbacd4536ba64aeca993f8f53&signature=lQISzeVILsdmVNRm6MFnnGrtLs5PHc7O5oM%2BWsTwrAsPQ5cm2DyDNE7YcBdzorEJebMMUG/oe4stFKSYj9xNAw%3D%3D"
  }
}

