GET /api/2.5/auctions/e0c4d484a95140569171138086703f23 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: https://lb.api-sandbox.ea2.openprocurement.net/api/2.3/auctions

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2019-01-28-000002", 
    "enquiryPeriod": {
      "startDate": "2019-01-28T12:32:17.146983+02:00", 
      "endDate": "2019-02-06T20:00:00+02:00"
    }, 
    "registrationFee": {
      "currency": "UAH", 
      "amount": 700.87
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2019-02-06T20:00:00+02:00", 
    "awardCriteria": "highestCost", 
    "owner": "broker", 
    "id": "e0c4d484a95140569171138086703f23", 
    "description": "description of appraisal auction", 
    "title": "футляри до державних нагород", 
    "tenderAttempts": 1, 
    "auctionParameters": {
      "type": "insider", 
      "dutchSteps": 88
    }, 
    "guarantee": {
      "currency": "UAH", 
      "amount": 1000.99
    }, 
    "dateModified": "2019-01-28T12:32:17.260260+02:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2019-01-28T12:32:17.146983+02:00", 
      "endDate": "2019-02-07T16:15:00+02:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2019-02-07T00:00:00+02:00"
    }, 
    "bankAccount": {
      "accountIdentification": [
        {
          "scheme": "accountNumber", 
          "id": "111111-8", 
          "description": "some description"
        }
      ], 
      "bankName": "name of bank"
    }, 
    "procurementMethodType": "appraisal.insider", 
    "date": "2019-01-28T12:32:17.260260+02:00", 
    "lotIdentifier": "Q24421K222", 
    "rectificationPeriod": {
      "startDate": "2019-01-28T12:32:17.146983+02:00", 
      "endDate": "2019-01-31T16:15:00+02:00", 
      "invalidationDate": "2019-01-28T12:32:17.257914+02:00"
    }, 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CPV", 
          "description": "Земельні ділянки", 
          "id": "51413000-0"
        }, 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "46ff602897964fdeb334c4a55e9bc9d7", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }
  }
}

