GET /api/2.5/auctions/0a3e5825752c49199ced43de14247e09 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb.api-sandbox.registry.ea.openprocurement.net

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2018-12-07-000002", 
    "enquiryPeriod": {
      "startDate": "2018-12-07T19:32:46.197484+02:00", 
      "endDate": "2018-12-20T20:00:00+02:00"
    }, 
    "registrationFee": {
      "currency": "UAH", 
      "amount": 700.87
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2018-12-20T20:00:00+02:00", 
    "awardCriteria": "highestCost", 
    "owner": "broker", 
    "id": "0a3e5825752c49199ced43de14247e09", 
    "title": "футляри до державних нагород", 
    "tenderAttempts": 1, 
    "auctionParameters": {
      "type": "insider", 
      "dutchSteps": 88
    }, 
    "dateModified": "2018-12-07T19:32:46.278565+02:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2018-12-07T19:32:46.197484+02:00", 
      "endDate": "2018-12-21T16:15:00+02:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2018-12-21T00:00:00+02:00"
    }, 
    "bankAccount": {
      "accountIdentification": [
        {
          "scheme": "accountNumber", 
          "id": "111111-8", 
          "description": "some description"
        }
      ], 
      "bankName": "name of bank"
    }, 
    "procurementMethodType": "appraisal.insider", 
    "date": "2018-12-07T19:32:46.278565+02:00", 
    "lotIdentifier": "Q24421K222", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CPV", 
          "description": "Земельні ділянки", 
          "id": "51413000-0"
        }, 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "6c318ef0d2954b0480d3310fe83d9266", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }
  }
}

