PATCH /api/2.5/auctions/0a3e5825752c49199ced43de14247e09/awards/f1dbe0f1df254b698f15398a43d79942?acc_token=2ae288c6a1204108bc3013241ac553eb HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: lb.api-sandbox.registry.ea.openprocurement.net
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "bid_owner", 
        "title": "SignedAuctionProtocol.pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/d94678530a8140178253836ae17c8afb?KeyID=172d32c8&Signature=fAOV7UZXfEw8oUGoZSyObb9TMbJK2A1U376Ohz4McIga0d2ufu7mCABtiP6ipU2bFo8RLlOBbWIH%2F4SGD%2F1vCg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "auction", 
        "datePublished": "2018-12-07T19:32:48.260451+02:00", 
        "documentType": "auctionProtocol", 
        "dateModified": "2018-12-07T19:32:48.260471+02:00", 
        "id": "13322079f72742e7933534f02cd7601d"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "auction_owner", 
        "title": "SignedAuctionProtocol.pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/78a1d7c337734c71b2942841190a694a?KeyID=172d32c8&Signature=Bwq936Hc3KHQrGs96q%252BrEXvKaCpy91Y4dENE1ZDw%252B5FkoeFWKMrNhqrMJfSpeSL2C8snOu5tuaYkUeDVE9ajAg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "auction", 
        "datePublished": "2018-12-07T19:32:48.354668+02:00", 
        "documentType": "auctionProtocol", 
        "dateModified": "2018-12-07T19:32:48.354687+02:00", 
        "id": "d42edd1abf044a16b546fc3558127548"
      }
    ], 
    "verificationPeriod": {
      "startDate": "2018-12-07T19:32:47.965330+02:00", 
      "endDate": "2018-12-07T19:32:48.473679+02:00"
    }, 
    "signingPeriod": {
      "startDate": "2018-12-07T19:32:47.965330+02:00", 
      "endDate": "2019-01-16T18:00:00+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "complaintPeriod": {
      "startDate": "2018-12-07T19:32:47.965330+02:00", 
      "endDate": "2018-12-07T19:32:48.473679+02:00"
    }, 
    "bid_id": "917fb2cdbacd4536ba64aeca993f8f53", 
    "value": {
      "currency": "UAH", 
      "amount": 479, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-12-07T19:32:48.488046+02:00", 
    "id": "f1dbe0f1df254b698f15398a43d79942"
  }
}

