POST /api/2.5/auctions?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2463
Content-Type: application/json
Host: https://lb.api-sandbox.ea2.openprocurement.net/api/2.3/auctions
DATA:
{
  "data": {
    "bankAccount": {
      "accountIdentification": [
        {
          "scheme": "accountNumber", 
          "id": "111111-8", 
          "description": "some description"
        }
      ], 
      "bankName": "name of bank"
    }, 
    "lotIdentifier": "Q24421K222", 
    "documents": [
      {
        "format": "application/msword", 
        "title": "укр.doc", 
        "accessDetails": "access details", 
        "documentType": "x_dgfAssetFamiliarization"
      }
    ], 
    "description": "description of appraisal auction", 
    "title": "футляри до державних нагород", 
    "auctionPeriod": {
      "startDate": "2019-02-07T12:32:10.895130"
    }, 
    "tenderAttempts": 1, 
    "procurementMethodType": "appraisal.insider", 
    "value": {
      "currency": "UAH", 
      "amount": 100
    }, 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }, 
    "title_ru": "футляры к государственным наградам", 
    "items": [
      {
        "classification": {
          "scheme": "CPV", 
          "id": "45255120-6", 
          "description": "Земельні ділянки"
        }, 
        "description": "Земля для військовослужбовців", 
        "id": "80fdd02d97304cdebb7fc6fbcdc0980f", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "auctionParameters": {
      "type": "insider", 
      "dutchSteps": 88
    }, 
    "title_en": "Cases with state awards", 
    "registrationFee": {
      "currency": "UAH", 
      "amount": 700.87
    }, 
    "guarantee": {
      "currency": "UAH", 
      "amount": 1000.99
    }
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://https://lb.api-sandbox.ea2.openprocurement.net/api/2.3/auctions/api/2.5/auctions/2a4f3f66ced44d0b9b014e0a814c01b8
X-Content-Type-Options: nosniff
{
  "access": {
    "transfer": "23333c81574b4a0881a13faabb465343", 
    "token": "453a05152a3e4685910c1f11cd7a08d4"
  }, 
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2019-01-28-000003", 
    "enquiryPeriod": {
      "startDate": "2019-01-28T12:32:17.344409+02:00", 
      "endDate": "2019-02-06T20:00:00+02:00"
    }, 
    "registrationFee": {
      "currency": "UAH", 
      "amount": 700.87
    }, 
    "submissionMethod": "electronicAuction", 
    "awardCriteria": "highestCost", 
    "owner": "broker", 
    "id": "2a4f3f66ced44d0b9b014e0a814c01b8", 
    "description": "description of appraisal auction", 
    "title": "футляри до державних нагород", 
    "tenderAttempts": 1, 
    "auctionParameters": {
      "type": "insider", 
      "dutchSteps": 88
    }, 
    "guarantee": {
      "currency": "UAH", 
      "amount": 1000.99
    }, 
    "dateModified": "2019-01-28T12:32:17.370791+02:00", 
    "status": "draft", 
    "tenderPeriod": {
      "startDate": "2019-01-28T12:32:17.344409+02:00", 
      "endDate": "2019-02-07T16:15:00+02:00"
    }, 
    "title_en": "Cases with state awards", 
    "bankAccount": {
      "accountIdentification": [
        {
          "scheme": "accountNumber", 
          "id": "111111-8", 
          "description": "some description"
        }
      ], 
      "bankName": "name of bank"
    }, 
    "procurementMethodType": "appraisal.insider", 
    "date": "2019-01-28T12:32:17.344409+02:00", 
    "lotIdentifier": "Q24421K222", 
    "rectificationPeriod": {
      "startDate": "2019-01-28T12:32:17.344409+02:00", 
      "endDate": "2019-01-31T16:15:00+02:00"
    }, 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "description": "Земля для військовослужбовців", 
        "id": "80fdd02d97304cdebb7fc6fbcdc0980f", 
        "classification": {
          "scheme": "CPV", 
          "description": "Земельні ділянки", 
          "id": "45255120-6"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "title_ru": "футляры к государственным наградам", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }
  }
}

