POST /api/2.5/auctions?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2343
Content-Type: application/json
Host: lb.api-sandbox.registry.ea.openprocurement.net
DATA:
{
  "data": {
    "bankAccount": {
      "accountIdentification": [
        {
          "scheme": "accountNumber", 
          "id": "111111-8", 
          "description": "some description"
        }
      ], 
      "bankName": "name of bank"
    }, 
    "lotIdentifier": "Q24421K222", 
    "documents": [
      {
        "format": "application/msword", 
        "title": "укр.doc", 
        "accessDetails": "access details", 
        "documentType": "x_dgfAssetFamiliarization"
      }
    ], 
    "title": "футляри до державних нагород", 
    "auctionPeriod": {
      "startDate": "2018-12-21"
    }, 
    "tenderAttempts": 1, 
    "procurementMethodType": "appraisal.insider", 
    "value": {
      "currency": "UAH", 
      "amount": 100
    }, 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }, 
    "title_ru": "футляры к государственным наградам", 
    "items": [
      {
        "classification": {
          "scheme": "CPV", 
          "id": "45255120-6", 
          "description": "Земельні ділянки"
        }, 
        "description": "Земля для військовослужбовців", 
        "id": "971975dbd9384856b693ec7e8cc39982", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "auctionParameters": {
      "type": "insider", 
      "dutchSteps": 88
    }, 
    "title_en": "Cases with state awards", 
    "registrationFee": {
      "currency": "UAH", 
      "amount": 700.87
    }
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb.api-sandbox.registry.ea.openprocurement.net/api/2.5/auctions/8cce67fe5acc42edaf36089bbb186c4d
X-Content-Type-Options: nosniff
{
  "access": {
    "transfer": "5f418678a3224f49a63ba07cb3da66d6", 
    "token": "73becd61bea04e399ec266b165b60754"
  }, 
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2018-12-07-000003", 
    "enquiryPeriod": {
      "startDate": "2018-12-07T19:32:46.350295+02:00", 
      "endDate": "2018-12-20T20:00:00+02:00"
    }, 
    "registrationFee": {
      "currency": "UAH", 
      "amount": 700.87
    }, 
    "submissionMethod": "electronicAuction", 
    "awardCriteria": "highestCost", 
    "owner": "broker", 
    "id": "8cce67fe5acc42edaf36089bbb186c4d", 
    "title": "футляри до державних нагород", 
    "tenderAttempts": 1, 
    "auctionParameters": {
      "type": "insider", 
      "dutchSteps": 88
    }, 
    "dateModified": "2018-12-07T19:32:46.373307+02:00", 
    "status": "draft", 
    "tenderPeriod": {
      "startDate": "2018-12-07T19:32:46.350295+02:00", 
      "endDate": "2018-12-21T16:15:00+02:00"
    }, 
    "title_en": "Cases with state awards", 
    "bankAccount": {
      "accountIdentification": [
        {
          "scheme": "accountNumber", 
          "id": "111111-8", 
          "description": "some description"
        }
      ], 
      "bankName": "name of bank"
    }, 
    "procurementMethodType": "appraisal.insider", 
    "date": "2018-12-07T19:32:46.350295+02:00", 
    "lotIdentifier": "Q24421K222", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "description": "Земля для військовослужбовців", 
        "id": "971975dbd9384856b693ec7e8cc39982", 
        "classification": {
          "scheme": "CPV", 
          "description": "Земельні ділянки", 
          "id": "45255120-6"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "title_ru": "футляры к государственным наградам", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }
  }
}

