GET /api/2.5/auctions/0a3e5825752c49199ced43de14247e09/awards HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb.api-sandbox.registry.ea.openprocurement.net

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": [
    {
      "status": "pending", 
      "verificationPeriod": {
        "startDate": "2018-12-07T19:32:47.965330+02:00", 
        "endDate": "2018-12-21T18:00:00+02:00"
      }, 
      "signingPeriod": {
        "startDate": "2018-12-07T19:32:47.965330+02:00", 
        "endDate": "2019-01-16T18:00:00+02:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "aagt@gmail.com", 
            "telephone": "+380 (322) 91-69-30", 
            "name": "Андрій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137226", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Книга»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 34", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ], 
      "complaintPeriod": {
        "startDate": "2018-12-07T19:32:47.965330+02:00"
      }, 
      "bid_id": "917fb2cdbacd4536ba64aeca993f8f53", 
      "value": {
        "currency": "UAH", 
        "amount": 479, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2018-12-07T19:32:47.965330+02:00", 
      "id": "f1dbe0f1df254b698f15398a43d79942"
    }, 
    {
      "status": "pending.waiting", 
      "complaintPeriod": {
        "startDate": "2018-12-07T19:32:47.965330+02:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "16331e49f073425798ea4f18f3590c95", 
      "value": {
        "currency": "UAH", 
        "amount": 469, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2018-12-07T19:32:47.965330+02:00", 
      "id": "6db7e816045d472988cfe99940d2e89f"
    }
  ]
}

