GET /api/2.5/auctions/e0c4d484a95140569171138086703f23/questions/8a9247bb32fe4b1abcc87d59d4b65f53 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: https://lb.api-sandbox.ea2.openprocurement.net/api/2.3/auctions

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "title": "Калорійність", 
    "date": "2019-01-28T12:32:18.382280+02:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "8a9247bb32fe4b1abcc87d59d4b65f53", 
    "questionOf": "tender"
  }
}

