POST /api/2.5/auctions/0a3e5825752c49199ced43de14247e09/cancellations?acc_token=2ae288c6a1204108bc3013241ac553eb HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: lb.api-sandbox.registry.ea.openprocurement.net
DATA:
{
  "data": {
    "reason": "cancellation reason"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb.api-sandbox.registry.ea.openprocurement.net/api/2.5/auctions/0a3e5825752c49199ced43de14247e09/cancellations/045327e6186f45c1bc77c967d8a04d9b
X-Content-Type-Options: nosniff
{
  "data": {
    "date": "2018-12-07T19:32:49.550603+02:00", 
    "status": "pending", 
    "reason": "cancellation reason", 
    "cancellationOf": "tender", 
    "id": "045327e6186f45c1bc77c967d8a04d9b"
  }
}

