POST /api/2.5/auctions/0a3e5825752c49199ced43de14247e09/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 741
Content-Type: application/json
Host: lb.api-sandbox.registry.ea.openprocurement.net
DATA:
{
  "data": {
    "qualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк", 
          "email": "aagt@gmail.com"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79013", 
          "region": "м. Львів", 
          "streetAddress": "вул. Островського, 34", 
          "locality": "м. Львів"
        }
      }
    ], 
    "value": {
      "amount": 501
    }, 
    "eligible": true
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb.api-sandbox.registry.ea.openprocurement.net/api/2.5/auctions/0a3e5825752c49199ced43de14247e09/bids/917fb2cdbacd4536ba64aeca993f8f53
X-Content-Type-Options: nosniff
{
  "access": {
    "token": "6cd7aafceb2046dda46579f952f05e05"
  }, 
  "data": {
    "status": "active", 
    "eligible": true, 
    "date": "2018-12-07T19:32:47.484789+02:00", 
    "qualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "owner": "broker", 
    "id": "917fb2cdbacd4536ba64aeca993f8f53", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/insider-auctions/0a3e5825752c49199ced43de14247e09/login?bidder_id=917fb2cdbacd4536ba64aeca993f8f53&signature=lQISzeVILsdmVNRm6MFnnGrtLs5PHc7O5oM%2BWsTwrAsPQ5cm2DyDNE7YcBdzorEJebMMUG/oe4stFKSYj9xNAw%3D%3D"
  }
}

