PUT /api/2.5/auctions/e0c4d484a95140569171138086703f23/cancellations/a26b6050db80408983ad92b6bca5f1c6/documents/fb5be37e1ada459ab4a05622f31541e4?acc_token=4cc54038a92f4f578a435ca9cb041343 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 327
Content-Type: application/json
Host: https://lb.api-sandbox.ea2.openprocurement.net/api/2.3/auctions
DATA:
{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/3f54300127784140bd8dc69c407ac851?KeyID=172d32c8&Signature=PxO3c07cLYGXhhtgqM4muUTOIeNRy2EoI2r0ZvSboFJCHsqqjGxOrOTGKFlBk2GGdTdJyFQkLG0dVp0NOobcBA%3D%3D", 
    "title": "Notice-2.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/3f54300127784140bd8dc69c407ac851?KeyID=172d32c8&Signature=70fWiI5taKEkiCIFmLijKvdnZ3jEemrJfFlLEbQ63JvQGRRO9WgMdUt57TSC0SMkEnlwsLRr%252BM1FsyQuNkDrAw%253D%253D", 
    "title": "Notice-2.pdf", 
    "documentOf": "auction", 
    "datePublished": "2019-01-28T12:32:22.306099+02:00", 
    "dateModified": "2019-01-28T12:32:22.792398+02:00", 
    "id": "fb5be37e1ada459ab4a05622f31541e4"
  }
}

