PUT /api/2.5/auctions/0a3e5825752c49199ced43de14247e09/cancellations/045327e6186f45c1bc77c967d8a04d9b/documents/893c8f3d3bb548b19abc14b88c0c67a2?acc_token=2ae288c6a1204108bc3013241ac553eb HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 337
Content-Type: application/json
Host: lb.api-sandbox.registry.ea.openprocurement.net
DATA:
{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/7163b262d208405c86553c860ba620de?KeyID=172d32c8&Signature=SvAPL3XdBZa8AIctjx7Ea40T3TWrpz%2FPJfGGZ5fYSZkYQqv%2FENpo8%2F4GiM0GoY%2BpQGeYEAFsUYjF%2Fzx9DqOUDQ%3D%3D", 
    "title": "Notice-2.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/7163b262d208405c86553c860ba620de?KeyID=172d32c8&Signature=Zrpkgil66ulLhPShf9%252BhuAD%2FySKQAvBJGTJVLYwufoV8E1bJseMIRy8MO2FziVnL2c%252BOquJbdx%2FUqLrASYs0Bw%253D%253D", 
    "title": "Notice-2.pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-12-07T19:32:49.678291+02:00", 
    "dateModified": "2018-12-07T19:32:49.953951+02:00", 
    "id": "893c8f3d3bb548b19abc14b88c0c67a2"
  }
}

