PUT /api/2.5/auctions/e0c4d484a95140569171138086703f23/documents/b85a9b4422084bd49a2885b32fe9b4b9?acc_token=4cc54038a92f4f578a435ca9cb041343 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 340
Content-Type: application/json
Host: https://lb.api-sandbox.ea2.openprocurement.net/api/2.3/auctions
DATA:
{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/53ef485f1a1f41b6a6fbad631572346c?KeyID=172d32c8&Signature=iGf3uU89QfT3uYjaki1iOM3cwLEK9edS1%2Bu9y7VKX7Nixog6vvI%2BQL9kVh23Dzgh52QK7bX%2BXQQqoAq4uraKBQ%3D%3D", 
    "title": "AwardCriteria-2.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "title": "AwardCriteria-2.pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/53ef485f1a1f41b6a6fbad631572346c?KeyID=172d32c8&Signature=zS2ipM2G7i8Y%252BpT9XNBXW2Hi9LM4x8w40wpyHXaZJRCymcX5BJLEELPBgK8SDWqB22j8DvskE1XSa75hh7n3Dg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "auction", 
    "datePublished": "2019-01-28T12:32:17.724608+02:00", 
    "dateModified": "2019-01-28T12:32:17.817955+02:00", 
    "id": "b85a9b4422084bd49a2885b32fe9b4b9"
  }
}

