POST /api/2.5/auctions/0a3e5825752c49199ced43de14247e09/contracts/52c8c00a6cbb4c23b9cba3a049f90bce/documents?acc_token=2ae288c6a1204108bc3013241ac553eb HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 377
Content-Type: application/json
Host: lb.api-sandbox.registry.ea.openprocurement.net
DATA:
{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/308046ba669a40e4b0fb6131821d57db?KeyID=172d32c8&Signature=6SBvK0GhnIPAq6Kd4DKeXIL8ZJBuBMEX80Q%2FCc0vaywmqzZS5KOT%2BtpI%2FrriA4%2FEKTmxvYpSJPYRh%2BCE%2FA0kDg%3D%3D", 
    "title": "signDocument.pdf", 
    "format": "application/pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "documentType": "contractSigned"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb.api-sandbox.registry.ea.openprocurement.net/api/2.5/auctions/0a3e5825752c49199ced43de14247e09/contracts/52c8c00a6cbb4c23b9cba3a049f90bce/documents/5ce1938047f647589624e127c55c4fd7
X-Content-Type-Options: nosniff
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "title": "signDocument.pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/308046ba669a40e4b0fb6131821d57db?KeyID=172d32c8&Signature=Tv%2FgWMW%252BUYsqR%252BvJ96EONdrQ81XjEUg0LUd0e0ai756iPQsDUuDoAIqDPz0ihUnk5TiStJL%252B0yLgoJ7LsO3qBA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "auction", 
    "datePublished": "2018-12-07T19:32:49.173081+02:00", 
    "documentType": "contractSigned", 
    "dateModified": "2018-12-07T19:32:49.173102+02:00", 
    "id": "5ce1938047f647589624e127c55c4fd7"
  }
}

