POST /api/2.5/auctions/e0c4d484a95140569171138086703f23/documents?acc_token=4cc54038a92f4f578a435ca9cb041343 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 432
Content-Type: application/json
Host: https://lb.api-sandbox.ea2.openprocurement.net/api/2.3/auctions
DATA:
{
  "data": {
    "index": 2, 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Second illustration description", 
    "title": "second_illustration.jpeg", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/8581590c05844a9c8d527b63232aff4a?KeyID=172d32c8&Signature=59BJ8pQObCY9eHUi9v5Bp%2B0s67mYVWCZWLR7Z5FVKYcWfzO4aDn1NNse3g1odrR4rJJhfS%2B6SClFFF2KAdUUCA%3D%3D", 
    "format": "image/jpeg", 
    "documentType": "illustration"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://https://lb.api-sandbox.ea2.openprocurement.net/api/2.3/auctions/api/2.5/auctions/e0c4d484a95140569171138086703f23/documents/84bace22f9114d8d98f2c9c06a858c6d
X-Content-Type-Options: nosniff
{
  "data": {
    "index": 2, 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Second illustration description", 
    "format": "image/jpeg", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/8581590c05844a9c8d527b63232aff4a?KeyID=172d32c8&Signature=4lr0rXnd1icb0cmt9itu1y2c1OWAZrI3nyi8JYtfY6llpSryb2sVvlV6HgGDJiJTYA4yW7OqXmMZXwZuzArxDA%253D%253D", 
    "title": "second_illustration.jpeg", 
    "documentOf": "auction", 
    "datePublished": "2019-01-28T12:32:18.049118+02:00", 
    "documentType": "illustration", 
    "dateModified": "2019-01-28T12:32:18.049168+02:00", 
    "id": "84bace22f9114d8d98f2c9c06a858c6d"
  }
}

